version: "3.8"

services:
  service:
    build:
      context: ./service
      args:
        - NODE_ENV=development
    environment:
      NODE_ENV: development
      PORT: 8480
      RPC_HOST: core
      RPC_PORT: 8455
      RPC_USER: localuser
      RPC_PASSWORD: devpass
    ports:
    - 8480:8480
    volumes:
    - ./service:/service:delegated
    - ./service/package.json:/service/package.json
    - /service/node_modules
    command: yarn dev

  core:
    build:
      context: ./docker
    volumes:
    - /root/.BGL
    ports:
    - 8455
